#!/usr/bin/env python3
"""Enforce prompt budgets with typed observation compaction and a last-resort summary."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Callable

if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[2]))

from drug_agent.protocol.react_protocol import parse_react_sequence


COMPACTION_SCHEMA = "react_context_budget_compaction_v3"
MICROCOMPACT_SCHEMA = "react_typed_observation_compaction_v2"
SUMMARY_HEADER = "[Compressed trajectory history; generated deterministically from earlier recorded turns.]"
LLM_SUMMARY_HEADER = "[Compressed trajectory history; generated by a grounded LLM summarizer from earlier recorded turns.]"
MICROCOMPACT_MIN_CHARS = 32_768
MICROCOMPACT_KEEP_RECENT_OBSERVATIONS = 4
SemanticSummarizer = Callable[[list[dict[str, Any]]], tuple[dict[str, Any], dict[str, Any]]]


def _token_count(value: Any) -> int:
    if hasattr(value, "keys"):
        value = value["input_ids"]
    if value and isinstance(value[0], list):
        value = value[0]
    return len(value)


def render_length(tokenizer, messages: list[dict[str, Any]]) -> int:
    encoded = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        enable_thinking=False,
    )
    return _token_count(encoded)


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()


def _compact_value(value: Any, *, string_limit: int = 512, depth: int = 0) -> Any:
    """Preserve scalar state while replacing bulky payloads with audited descriptors."""
    if depth >= 5:
        text = json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)
        return {"type": type(value).__name__, "chars": len(text), "sha256": _sha256_text(text)}
    if value is None or isinstance(value, (bool, int, float)):
        return value
    if isinstance(value, str):
        if len(value) <= string_limit:
            return value
        return {
            "type": "string",
            "chars": len(value),
            "sha256": _sha256_text(value),
            "head": value[:160],
            "tail": value[-160:],
        }
    if isinstance(value, list):
        if len(value) <= 12:
            return [_compact_value(item, string_limit=string_limit, depth=depth + 1) for item in value]
        text = json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)
        return {
            "type": "list",
            "items": len(value),
            "sha256": _sha256_text(text),
            "head": [_compact_value(item, string_limit=160, depth=depth + 1) for item in value[:4]],
            "tail": [_compact_value(item, string_limit=160, depth=depth + 1) for item in value[-4:]],
        }
    if isinstance(value, dict):
        preferred = (
            "ok", "status", "error", "error_message", "message", "tool_name", "path", "file_path",
            "input_path", "output_path", "output_file", "artifact", "artifact_id", "id", "content", "metadata",
        )
        keys = list(value)
        ordered = [key for key in preferred if key in value]
        ordered.extend(sorted((key for key in keys if key not in ordered), key=str)[: max(0, 32 - len(ordered))])
        out = {
            str(key): _compact_value(value[key], string_limit=string_limit, depth=depth + 1)
            for key in ordered[:32]
        }
        if len(keys) > len(out):
            text = json.dumps(value, ensure_ascii=False, sort_keys=True, default=str)
            out["_omitted_keys"] = len(keys) - len(out)
            out["_sha256"] = _sha256_text(text)
        return out
    text = str(value)
    return _compact_value(text, string_limit=string_limit, depth=depth + 1)


def _canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), default=str)


def _render_observation_message(blocks: list[dict[str, Any]]) -> str:
    rendered = []
    for block in blocks:
        tool_name = str(block.get("tool_name") or "")
        rendered.append(
            f"<observation tool_name={json.dumps(tool_name, ensure_ascii=False)}>"
            + _canonical_json(block.get("payload") or {})
            + "</observation>"
        )
    return "".join(rendered)


def _microcompact_old_observations(
    prompt: list[dict[str, Any]],
    *,
    min_chars: int = MICROCOMPACT_MIN_CHARS,
    keep_recent: int = MICROCOMPACT_KEEP_RECENT_OBSERVATIONS,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Clear bulky leaves from old tool results while preserving call/result pairing."""
    output = copy.deepcopy(prompt)
    parsed_messages: dict[int, list[dict[str, Any]]] = {}
    observation_indices = []
    for message_index, message in enumerate(prompt):
        if not isinstance(message, dict) or message.get("role") != "user":
            continue
        parsed = parse_react_sequence(str(message.get("content") or ""), role="user")
        blocks = parsed.get("blocks") if parsed.get("ok") else []
        if blocks and all(block.get("kind") == "observation" for block in blocks):
            parsed_messages[message_index] = blocks
            observation_indices.append(message_index)

    protected = set(observation_indices[-keep_recent:]) if keep_recent else set()
    entries = []
    for message_index in observation_indices:
        if message_index in protected:
            continue
        blocks = copy.deepcopy(parsed_messages[message_index])
        changed = False
        for block_index, block in enumerate(blocks):
            payload = block.get("payload") if isinstance(block.get("payload"), dict) else {}
            raw = _canonical_json(payload)
            if len(raw) < min_chars:
                continue
            compacted = _compact_value(payload)
            if not isinstance(compacted, dict):
                compacted = {"value": compacted}
            compacted["_microcompact"] = {
                "schema_version": MICROCOMPACT_SCHEMA,
                "original_chars": len(raw),
                "sha256": _sha256_text(raw),
            }
            compacted_raw = _canonical_json(compacted)
            if len(compacted_raw) >= len(raw):
                continue
            block["payload"] = compacted
            changed = True
            entries.append(
                {
                    "message_index": message_index,
                    "block_index": block_index,
                    "tool_name": str(block.get("tool_name") or ""),
                    "original_chars": len(raw),
                    "output_chars": len(compacted_raw),
                    "sha256": _sha256_text(raw),
                }
            )
        if changed:
            output[message_index]["content"] = _render_observation_message(blocks)

    characters_freed = sum(entry["original_chars"] - entry["output_chars"] for entry in entries)
    return output, {
        "schema_version": MICROCOMPACT_SCHEMA,
        "min_result_chars": min_chars,
        "keep_recent_observations": keep_recent,
        "eligible_observation_messages": len(observation_indices),
        "protected_recent_observation_messages": len(protected),
        "compacted_observation_blocks": len(entries),
        "characters_freed": characters_freed,
        "estimated_tokens_freed": characters_freed // 4,
        "entries": entries,
    }


def _summarize_message(message: dict[str, Any], message_index: int) -> tuple[dict[str, Any], list[str]]:
    role = str(message.get("role") or "")
    content = str(message.get("content") or "")
    parsed = parse_react_sequence(content, role=role)
    tool_names: list[str] = []
    entry: dict[str, Any] = {"message_index": message_index, "role": role}
    if parsed.get("ok"):
        blocks = []
        for block in parsed.get("blocks") or []:
            kind = block.get("kind")
            if kind == "thought":
                blocks.append({"kind": "rationale", "text": _compact_value(block.get("text") or "", string_limit=256)})
            elif kind == "tool_call":
                tool_name = str(block.get("tool_name") or "")
                tool_names.append(tool_name)
                blocks.append(
                    {
                        "kind": "tool_call",
                        "tool_name": tool_name,
                        "arguments": _compact_value(block.get("arguments") or {}),
                    }
                )
            elif kind == "observation":
                tool_name = str(block.get("tool_name") or "")
                blocks.append(
                    {
                        "kind": "observation",
                        "tool_name": tool_name,
                        "result": _compact_value(block.get("payload") or {}),
                    }
                )
            elif kind == "final_answer":
                blocks.append({"kind": "final_answer", "value": _compact_value(block.get("payload") or {})})
        entry["blocks"] = blocks
    else:
        entry["content"] = _compact_value(content)
        entry["parse_error"] = parsed.get("error_message")
    return entry, tool_names


def _summary_content(tokenizer, omitted: list[dict[str, Any]], summary_max_tokens: int) -> tuple[str, dict[str, Any]]:
    details: list[dict[str, Any]] = []
    tool_counts: Counter[str] = Counter()
    for message_index, message in enumerate(omitted):
        entry, tool_names = _summarize_message(message, message_index)
        details.append(entry)
        tool_counts.update(name for name in tool_names if name)

    collapsed = 0
    attempts = 0
    while True:
        payload = {
            "schema_version": COMPACTION_SCHEMA,
            "collapsed_older_messages": collapsed,
            "collapsed_tool_counts": dict(sorted(tool_counts.items())),
            "recent_history": details[collapsed:],
        }
        content = SUMMARY_HEADER + "\n" + json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        ids = tokenizer.encode(content, add_special_tokens=False)
        attempts += 1
        if len(ids) <= summary_max_tokens or collapsed >= len(details):
            return content, {
                "summary_tokens": len(ids),
                "summarized_messages": len(omitted),
                "collapsed_older_messages": collapsed,
                "summary_sha256": _sha256_text(content),
                "summary_fit_attempts": attempts,
            }
        remaining = len(details) - collapsed
        # Jump close to the required compression ratio instead of repeatedly
        # deleting one eighth of a potentially huge history.
        keep = max(0, int(remaining * summary_max_tokens / max(1, len(ids)) * 0.90))
        next_collapsed = len(details) - keep
        collapsed = max(collapsed + 1, next_collapsed)


def _semantic_compaction(
    tokenizer,
    working_prompt: list[dict[str, Any]],
    *,
    max_tokens: int,
    summary_max_tokens: int,
    semantic_summarizer: SemanticSummarizer,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    prefix = copy.deepcopy(working_prompt[:2])
    suffix_starts = [index for index in range(2, len(working_prompt)) if working_prompt[index].get("role") == "assistant"]
    suffix_starts.append(len(working_prompt))
    marker = {"role": "user", "content": LLM_SUMMARY_HEADER}

    # Find the earliest complete assistant/observation suffix while reserving
    # the entire summary budget. This avoids invoking the external LLM during
    # suffix search and guarantees one summary artifact per unique prefix.
    low, high = 0, len(suffix_starts) - 1
    selected = None
    while low <= high:
        middle = (low + high) // 2
        start = suffix_starts[middle]
        base_tokens = render_length(tokenizer, prefix + [marker] + working_prompt[start:])
        if base_tokens + summary_max_tokens + 64 <= max_tokens:
            selected = middle
            high = middle - 1
        else:
            low = middle + 1
    if selected is None:
        raise ValueError("system/task prefix leaves no room for the semantic summary budget")

    suffix_start = suffix_starts[selected]
    omitted = []
    for source_message_index, message in enumerate(working_prompt[2:suffix_start], start=2):
        annotated = copy.deepcopy(message)
        annotated["_source_message_index"] = source_message_index
        omitted.append(annotated)
    summary, llm_audit = semantic_summarizer(omitted)
    content = LLM_SUMMARY_HEADER + "\n" + _canonical_json(summary)
    summary_tokens = len(tokenizer.encode(content, add_special_tokens=False))
    if summary_tokens > summary_max_tokens:
        raise ValueError(
            f"semantic summary exceeds budget: {summary_tokens} > {summary_max_tokens}"
        )
    messages = prefix + [{"role": "user", "content": content}] + copy.deepcopy(working_prompt[suffix_start:])
    output_tokens = render_length(tokenizer, messages)
    if output_tokens > max_tokens:
        raise ValueError(f"semantic compaction exceeded prompt budget: {output_tokens} > {max_tokens}")
    return messages, {
        "summary_tokens": summary_tokens,
        "summarized_messages": len(omitted),
        "collapsed_older_messages": 0,
        "summary_sha256": _sha256_text(content),
        "summary_fit_attempts": 1,
        "semantic_summary": llm_audit,
        "preserved_suffix_start": suffix_start,
    }


def compact_prompt_with_audit(
    tokenizer,
    prompt: list[dict[str, Any]],
    max_tokens: int,
    *,
    summary_max_tokens: int = 32768,
    semantic_summarizer: SemanticSummarizer | None = None,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    original_tokens = render_length(tokenizer, prompt)
    if original_tokens <= max_tokens:
        return copy.deepcopy(prompt), {
            "schema_version": COMPACTION_SCHEMA,
            "compacted": False,
            "original_tokens": original_tokens,
            "output_tokens": original_tokens,
            "original_messages": len(prompt),
            "output_messages": len(prompt),
        }
    if len(prompt) < 3:
        raise ValueError(f"oversized prompt has only {len(prompt)} messages")

    # Microcompact first: keep tool calls and message topology intact, and
    # replace only bulky leaves in older results. This mirrors Claude Code's
    # inexpensive first compression tier without its online cache-edit state.
    working_prompt, microcompact_audit = _microcompact_old_observations(prompt)
    microcompact_tokens = (
        original_tokens
        if not microcompact_audit.get("compacted_observation_blocks")
        else render_length(tokenizer, working_prompt)
    )
    if microcompact_tokens <= max_tokens:
        return working_prompt, {
            "schema_version": COMPACTION_SCHEMA,
            "compacted": True,
            "strategy": "microcompact_only",
            "levels_applied": ["typed_observation_compaction"],
            "original_tokens": original_tokens,
            "output_tokens": microcompact_tokens,
            "original_messages": len(prompt),
            "output_messages": len(working_prompt),
            "removed_messages": 0,
            "preserved_suffix_start": 2,
            "summary_max_tokens": summary_max_tokens,
            "summary_tokens": 0,
            "summarized_messages": 0,
            "collapsed_older_messages": 0,
            "summary_sha256": None,
            "microcompact": microcompact_audit,
        }

    if semantic_summarizer is not None:
        messages, summary_audit = _semantic_compaction(
            tokenizer,
            working_prompt,
            max_tokens=max_tokens,
            summary_max_tokens=summary_max_tokens,
            semantic_summarizer=semantic_summarizer,
        )
        return messages, {
            "schema_version": COMPACTION_SCHEMA,
            "compacted": True,
            "strategy": "microcompact_then_llm_summary",
            "levels_applied": ["typed_observation_compaction", "recent_history_preservation", "llm_semantic_summary"],
            "original_tokens": original_tokens,
            "output_tokens": render_length(tokenizer, messages),
            "original_messages": len(prompt),
            "output_messages": len(messages),
            "removed_messages": int(summary_audit["summarized_messages"]),
            "summary_max_tokens": summary_max_tokens,
            "microcompact_tokens": microcompact_tokens,
            "microcompact": microcompact_audit,
            **summary_audit,
        }

    prefix = copy.deepcopy(working_prompt[:2])
    if render_length(tokenizer, prefix) >= max_tokens:
        raise ValueError("system/task prefix alone exceeds the prompt budget")

    suffix_starts = [index for index in range(2, len(working_prompt)) if working_prompt[index].get("role") == "assistant"]
    suffix_starts.append(len(working_prompt))
    best: tuple[list[dict[str, Any]], dict[str, Any], int] | None = None
    cache: dict[int, tuple[list[dict[str, Any]], dict[str, Any], int]] = {}

    def candidate(position: int) -> tuple[list[dict[str, Any]], dict[str, Any], int]:
        if position in cache:
            return cache[position]
        start = suffix_starts[position]
        content, summary_audit = _summary_content(tokenizer, working_prompt[2:start], summary_max_tokens)
        messages = prefix + [{"role": "user", "content": content}] + copy.deepcopy(working_prompt[start:])
        length = render_length(tokenizer, messages)
        cache[position] = (messages, summary_audit, length)
        return cache[position]

    # Use the already measured token/character ratio to start close to the
    # boundary.  This avoids repeatedly tokenizing multi-megabyte overlapping
    # suffixes during a binary search.
    content_chars = [len(str(message.get("content") or "")) for message in working_prompt]
    total_chars = max(1, sum(content_chars))
    tokens_per_char = microcompact_tokens / total_chars
    prefix_tokens = render_length(tokenizer, prefix)
    suffix_token_budget = max(0, max_tokens - prefix_tokens - summary_max_tokens - 64)
    suffix_char_budget = int(suffix_token_budget / max(tokens_per_char, 1e-6))
    suffix_chars = 0
    position = len(suffix_starts) - 1
    for candidate_position in range(len(suffix_starts) - 2, -1, -1):
        start = suffix_starts[candidate_position]
        next_start = suffix_starts[candidate_position + 1]
        addition = sum(content_chars[start:next_start])
        if suffix_chars + addition > suffix_char_budget:
            break
        suffix_chars += addition
        position = candidate_position

    # Refine around the estimate.  Each jump is based on the measured gap, so
    # long histories normally need only two or three full chat-template calls.
    for _ in range(8):
        messages, summary_audit, length = candidate(position)
        if length <= max_tokens:
            best = (messages, summary_audit, position)
            if position == 0:
                break
            slack_chars = int((max_tokens - length) / max(tokens_per_char, 1e-6) * 0.9)
            earlier = position - 1
            while earlier > 0:
                added = sum(content_chars[suffix_starts[earlier] : suffix_starts[position]])
                if added > slack_chars:
                    break
                earlier -= 1
            next_position = max(0, earlier)
            if next_position == position:
                break
            position = next_position
        else:
            if position >= len(suffix_starts) - 1:
                break
            excess_chars = int((length - max_tokens) / max(tokens_per_char, 1e-6) * 1.1)
            later = position + 1
            while later < len(suffix_starts) - 1:
                removed = sum(content_chars[suffix_starts[position] : suffix_starts[later]])
                if removed >= excess_chars:
                    break
                later += 1
            position = later

    if best is None:
        messages, summary_audit, length = candidate(len(suffix_starts) - 1)
        if length > max_tokens:
            raise ValueError("structured summary cannot fit within the requested prompt budget")
        best = (messages, summary_audit, len(suffix_starts) - 1)

    # One exact predecessor check establishes the maximal contiguous suffix
    # under the locally monotone history-length boundary.
    if best[2] > 0:
        messages, summary_audit, length = candidate(best[2] - 1)
        if length <= max_tokens:
            best = (messages, summary_audit, best[2] - 1)

    messages, summary_audit, position = best
    output_tokens = render_length(tokenizer, messages)
    if output_tokens > max_tokens:
        raise AssertionError(f"compaction exceeded budget: {output_tokens} > {max_tokens}")
    suffix_start = suffix_starts[position]
    audit = {
        "schema_version": COMPACTION_SCHEMA,
        "compacted": True,
        "strategy": "microcompact_then_structured_summary",
        "levels_applied": ["typed_observation_compaction", "recent_history_preservation", "semantic_summary_fallback"],
        "original_tokens": original_tokens,
        "output_tokens": output_tokens,
        "original_messages": len(prompt),
        "output_messages": len(messages),
        "removed_messages": max(0, suffix_start - 2),
        "preserved_suffix_start": suffix_start,
        "summary_max_tokens": summary_max_tokens,
        "microcompact_tokens": microcompact_tokens,
        "microcompact": microcompact_audit,
        **summary_audit,
    }
    return messages, audit


def compact_prompt(tokenizer, prompt: list[dict], max_tokens: int) -> tuple[list[dict], int, int]:
    compacted, audit = compact_prompt_with_audit(tokenizer, prompt, max_tokens)
    return compacted, int(audit["original_tokens"]), int(audit["output_tokens"])


def main() -> None:
    from transformers import AutoTokenizer
    from drug_agent.context_summary import ClaudeContextSummarizer

    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--audit", type=Path, required=True)
    parser.add_argument("--tokenizer", required=True)
    parser.add_argument("--max-tokens", type=int, default=245760)
    parser.add_argument("--summary-max-tokens", type=int, default=32768)
    parser.add_argument("--max-response-tokens", type=int, default=16384)
    parser.add_argument("--max-context-tokens", type=int, default=262144)
    parser.add_argument("--semantic-summarizer", choices=("none", "claude"), default="none")
    parser.add_argument("--summary-cache-root", type=Path)
    parser.add_argument("--claude-bin", default="claude")
    parser.add_argument("--llm-timeout-sec", type=float, default=600.0)
    parser.add_argument("--llm-max-attempts", type=int, default=3)
    parser.add_argument("--excluded", type=Path)
    args = parser.parse_args()

    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer, trust_remote_code=True)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.audit.parent.mkdir(parents=True, exist_ok=True)
    excluded_path = args.excluded or args.output.with_suffix(args.output.suffix + ".excluded.jsonl")
    excluded_path.parent.mkdir(parents=True, exist_ok=True)
    summarizer = None
    if args.semantic_summarizer == "claude":
        if args.summary_cache_root is None:
            raise SystemExit("--summary-cache-root is required for --semantic-summarizer claude")
        summarizer = ClaudeContextSummarizer(
            cache_root=args.summary_cache_root,
            claude_bin=args.claude_bin,
            timeout_sec=args.llm_timeout_sec,
            max_attempts=args.llm_max_attempts,
        )
    input_records = records = compacted_count = original_max = output_max = 0
    row_audits = []
    excluded_rows = []
    with args.input.open(encoding="utf-8") as source, args.output.open("w", encoding="utf-8") as destination:
        for line_number, line in enumerate(source, 1):
            input_records += 1
            record = json.loads(line)
            target = record.get("teacher_response")
            if not isinstance(target, str):
                target_assistant = record.get("target_assistant")
                if isinstance(target_assistant, dict):
                    target = target_assistant.get("content")
            if not isinstance(target, str):
                label = record.get("label") if isinstance(record.get("label"), dict) else {}
                target = label.get("teacher_response")
            target_tokens = len(tokenizer.encode(str(target or ""), add_special_tokens=False))
            if target_tokens > args.max_response_tokens:
                excluded_rows.append({
                    "source_line": line_number,
                    "source_id": (record.get("metadata") or {}).get("source_id"),
                    "reason": "target_exceeds_response_limit",
                    "target_tokens": target_tokens,
                })
                continue
            try:
                compacted, audit = compact_prompt_with_audit(
                    tokenizer,
                    record["prompt"],
                    args.max_tokens,
                    summary_max_tokens=args.summary_max_tokens,
                    semantic_summarizer=(
                        lambda messages: summarizer.summarize(
                            messages, tokenizer=tokenizer, max_tokens=max(1, args.summary_max_tokens - 128)
                        )
                    ) if summarizer is not None else None,
                )
            except Exception as exc:
                excluded_rows.append({
                    "source_line": line_number,
                    "source_id": (record.get("metadata") or {}).get("source_id"),
                    "reason": "context_compaction_failed",
                    "error_type": type(exc).__name__,
                    "error": str(exc),
                })
                continue
            if int(audit["output_tokens"]) + target_tokens > args.max_context_tokens:
                excluded_rows.append({
                    "source_line": line_number,
                    "source_id": (record.get("metadata") or {}).get("source_id"),
                    "reason": "context_exceeds_limit",
                    "prompt_tokens": int(audit["output_tokens"]),
                    "target_tokens": target_tokens,
                })
                continue
            if audit["compacted"]:
                metadata = copy.deepcopy(record.get("metadata") or {})
                metadata["context_compaction"] = {**audit, "source_line": line_number, "target_tokens": target_tokens}
                record["metadata"] = metadata
                record["prompt"] = compacted
                if isinstance(record.get("state_messages"), list):
                    record["state_messages"] = copy.deepcopy(compacted)
                if isinstance(metadata.get("state_messages"), list):
                    metadata["state_messages"] = copy.deepcopy(compacted)
                compacted_count += 1
                row_audits.append({"source_line": line_number, **audit})
            destination.write(json.dumps(record, ensure_ascii=False, separators=(",", ":")) + "\n")
            records += 1
            original_max = max(original_max, int(audit["original_tokens"]))
            output_max = max(output_max, int(audit["output_tokens"]))

    with excluded_path.open("w", encoding="utf-8") as handle:
        for row in excluded_rows:
            handle.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")

    manifest = {
        "schema_version": COMPACTION_SCHEMA,
        "source": str(args.input.resolve()),
        "output": str(args.output.resolve()),
        "tokenizer": args.tokenizer,
        "max_tokens": args.max_tokens,
        "summary_max_tokens": args.summary_max_tokens,
        "max_response_tokens": args.max_response_tokens,
        "max_context_tokens": args.max_context_tokens,
        "semantic_summarizer": args.semantic_summarizer,
        "summary_cache_root": str(args.summary_cache_root.resolve()) if args.summary_cache_root else None,
        "input_records": input_records,
        "records": records,
        "compacted_records": compacted_count,
        "unchanged_records": records - compacted_count,
        "original_max_tokens": original_max,
        "output_max_tokens": output_max,
        "excluded_records": len(excluded_rows),
        "excluded_path": str(excluded_path.resolve()),
        "rows": row_audits,
    }
    args.audit.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
